#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude node_modules \
	. 'umsteigen.jetzt-rest:~/umsteigen.jetzt-rest/'

ssh umsteigen.jetzt-rest "\
cd ~/umsteigen.jetzt-rest
npm i
npm update
forever stop umsteigen.jetzt-rest
export NODE_ENV=production
forever start -a --uid umsteigen.jetzt-rest index.js"
